# File: simple-param.yml
parameters:
- name: action # name of the parameter; required
  type: string # data type of the parameter; required
  default: "deploy"

jobs:
- job: 'cdktf'
  displayName: 'CDKTF'

  container: 'mabivolan/mct:latest'

  steps:
  - script: |
      pipenv install

      source config.sh

      cdktf ${{ parameters.action }} --auto-approve
    displayName: 'CDKTF'